# Generated by Django 2.2.2 on 2019-11-25 16:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('Server', models.CharField(choices=[('EUW', 'EUW'), ('EUNE', 'EUNE'), ('NA', 'NA')], max_length=6)),
                ('Buyer_Email', models.EmailField(max_length=254, null=True)),
                ('UUID', models.UUIDField(default=uuid.uuid4)),
                ('bought', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('UUID', models.CharField(max_length=36)),
                ('server', models.CharField(max_length=10)),
                ('Buyer_Email', models.EmailField(max_length=254, null=True)),
                ('StripePaymentID', models.CharField(max_length=500)),
                ('PaymentConfirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
